    - name: Install and start httpd
      import_tasks: install_and_enable.yml
      vars:
        package: httpd
        service: httpd

    - name: Tuning configuration installed
      copy:
        src: files/tune.conf
        dest: /etc/httpd/conf.d/tune.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - restart httpd


